version: '3.8'

services:
  web_dev:
    build: .
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev

  db_dev:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5433:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db_dev

volumes:
  postgres_data_dev: